### ISSUE TITLE
Zeus assignment breaks current zeus modules

### ISSUE THREAD

**Issue by VexA3** [7Cav/7Cav_FullSpectrum_V4.Altis#237] opened 2019-08-03 19:39 UTC
Causing them to have to re-load into zeus constantly.

**Comment by BojanOnTheInternet** [comment] 2019-08-03 19:48
Duplicate of this:

https://github.com/7Cav/7Cav_FullSpectrum_V4.Altis/issues/155

**Closed by BojanOnTheInternet** 2019-08-03 19:48 UTC
Labels: wip
